// Detects drift between TypeScript declarations in specs/*.md and exported
// symbols in src/. For each `interface`/`type` declared in a ```typescript```
// block of a spec, if the same name is exported anywhere under src/, the
// script asks tsc whether the two are bidirectionally assignable. Any
// divergence is reported with the underlying tsc message.
//
// Each spec code block is processed in isolation (unique block prefix) so
// that names duplicated across specs don't collide as tsc duplicate
// identifiers.
//
// Run:
//   node --experimental-strip-types ~/.claude/scripts/spec-drift/src/spec-drift.ts \
//     [--specs-dir <path>] [--src-dir <path>] [--show-missing] [--json <path>]
//
// Paths default to <cwd>/specs and <cwd>/src. If either is missing, the
// script exits 0 with a "not spec-driven, skipping" notice — safe to wire
// unconditionally into a post-implementation workflow.
//
// --json <path> writes a machine-readable report to <path> with fields
// { skill, exit_code, checked_count, drift[], missing_count }. Each drift
// entry includes a synthetic id for oscillation hashing by loop-clean.sh.
// The console report is unaffected by this flag.
//
// Exit: 0 = no drift (or skipped), 1 = drift detected.

import { createHash } from "node:crypto";
import {
	existsSync,
	readdirSync,
	readFileSync,
	realpathSync,
	statSync,
	unlinkSync,
	writeFileSync,
} from "node:fs";
import { tmpdir } from "node:os";
import { dirname, isAbsolute, join, relative, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import ts from "typescript";

const SPEC_ONLY_MARKER = "// spec-only";

interface SpecBlock {
	specFile: string;
	line: number; // 1-based, opening ``` fence
	body: string; // raw block content
	declaredNames: string[]; // top-level interface/type names
	prefix: string; // e.g. "B007_"
}

export interface CheckedDecl {
	name: string;
	specFile: string;
	line: number;
	prefix: string;
	srcFile: string;
	status: "OK" | "DRIFT";
	detail?: string;
}

export interface MissingDecl {
	name: string;
	specFile: string;
	line: number;
}

function walkTsFiles(dir: string, out: string[]): void {
	for (const entry of readdirSync(dir)) {
		const p = join(dir, entry);
		const st = statSync(p);
		if (st.isDirectory()) walkTsFiles(p, out);
		else if (entry.endsWith(".ts") && !entry.endsWith(".d.ts")) out.push(p);
	}
}

function indexSrcExports(srcDir: string): Map<string, string> {
	const map = new Map<string, string>();
	const files: string[] = [];
	walkTsFiles(srcDir, files);
	for (const file of files) {
		const text = readFileSync(file, "utf8");
		const sf = ts.createSourceFile(file, text, ts.ScriptTarget.Latest, true);
		sf.forEachChild((node) => {
			if (!ts.isInterfaceDeclaration(node) && !ts.isTypeAliasDeclaration(node))
				return;
			const exported = node.modifiers?.some(
				(m) => m.kind === ts.SyntaxKind.ExportKeyword,
			);
			if (!exported) return;
			if (!map.has(node.name.text)) map.set(node.name.text, file);
		});
	}
	return map;
}

function extractBlocks(
	specFile: string,
	blockCounter: { n: number },
): SpecBlock[] {
	const text = readFileSync(specFile, "utf8");
	const blocks: SpecBlock[] = [];
	// Tolerate trailing whitespace / CRLF / extra attributes after the language tag.
	const blockRegex = /```(?:typescript|ts)[^\n]*\n([\s\S]*?)```/g;
	while (true) {
		const match = blockRegex.exec(text);
		if (match === null) break;
		const body = match[1];
		if (body.includes(SPEC_ONLY_MARKER)) continue;
		const lineNumber = text.slice(0, match.index).split("\n").length;
		const sf = ts.createSourceFile(
			"block.ts",
			body,
			ts.ScriptTarget.Latest,
			true,
		);
		const names: string[] = [];
		sf.forEachChild((node) => {
			if (ts.isInterfaceDeclaration(node) || ts.isTypeAliasDeclaration(node)) {
				names.push(node.name.text);
			}
		});
		if (names.length === 0) continue;
		blockCounter.n += 1;
		blocks.push({
			specFile,
			line: lineNumber,
			body,
			declaredNames: names,
			prefix: `B${String(blockCounter.n).padStart(4, "0")}_`,
		});
	}
	return blocks;
}

// Whole-word rename. Sufficient for ASCII identifier names used in this repo.
function renameAll(body: string, names: string[], prefix: string): string {
	let out = body;
	for (const n of names) {
		out = out.replace(new RegExp(`\\b${n}\\b`, "g"), `${prefix}${n}`);
	}
	return out;
}

function buildAssertionFile(
	blocks: SpecBlock[],
	srcMap: Map<string, string>,
	tmpFile: string,
): { checked: CheckedDecl[]; missing: MissingDecl[] } {
	const checked: CheckedDecl[] = [];
	const missing: MissingDecl[] = [];

	let content = "// AUTO-GENERATED by spec-drift.ts — DO NOT COMMIT\n\n";
	const importLines: string[] = [];
	const declLines: string[] = [];

	for (const block of blocks) {
		const renamed = renameAll(
			block.body,
			block.declaredNames,
			`Spec_${block.prefix}`,
		);
		declLines.push(renamed);

		for (const name of block.declaredNames) {
			const srcFile = srcMap.get(name);
			if (!srcFile) {
				missing.push({ name, specFile: block.specFile, line: block.line });
				continue;
			}
			// Path resolved from the tmp file's directory, not ROOT.
			const relPath = relative(dirname(tmpFile), srcFile).replace(/\\/g, "/");
			const rel = `${relPath.startsWith(".") ? "" : "./"}${relPath.replace(/\.ts$/, ".js")}`;
			const actualAlias = `Actual_${block.prefix}${name}`;
			const specAlias = `Spec_${block.prefix}${name}`;
			importLines.push(
				`import type { ${name} as ${actualAlias} } from "${rel}";`,
			);
			declLines.push(
				`const _a_${block.prefix}${name}: ${specAlias} = {} as ${actualAlias};`,
			);
			declLines.push(
				`const _b_${block.prefix}${name}: ${actualAlias} = {} as ${specAlias};`,
			);
			checked.push({
				name,
				specFile: block.specFile,
				line: block.line,
				prefix: block.prefix,
				srcFile,
				status: "OK",
			});
		}
		declLines.push("");
	}

	content += `${importLines.join("\n")}\n\n${declLines.join("\n")}`;
	writeFileSync(tmpFile, content);
	return { checked, missing };
}

function runTsc(tmpFile: string): readonly ts.Diagnostic[] {
	const program = ts.createProgram([tmpFile], {
		noEmit: true,
		strict: true,
		target: ts.ScriptTarget.ES2022,
		module: ts.ModuleKind.ESNext,
		moduleResolution: ts.ModuleResolutionKind.Bundler,
		skipLibCheck: true,
		esModuleInterop: true,
	});
	return ts.getPreEmitDiagnostics(program);
}

function classify(
	checked: CheckedDecl[],
	diags: readonly ts.Diagnostic[],
): void {
	for (const diag of diags) {
		const msg = ts.flattenDiagnosticMessageText(diag.messageText, "\n");
		// Each diagnostic mentions our unique tag at least once. Find it.
		for (const c of checked) {
			const tag = `${c.prefix}${c.name}`;
			if (msg.includes(tag)) {
				c.status = "DRIFT";
				c.detail = c.detail ? `${c.detail}\n${msg}` : msg;
				break;
			}
		}
	}
}

function printReport(
	checked: CheckedDecl[],
	missing: MissingDecl[],
	showMissing: boolean,
	root: string,
): number {
	const drift = checked.filter((c) => c.status === "DRIFT");
	const ok = checked.length - drift.length;

	console.log(
		`Spec drift report: ${ok} OK, ${drift.length} DRIFT${showMissing ? `, ${missing.length} MISSING_IN_CODE` : ""}`,
	);
	if (!showMissing && missing.length > 0) {
		console.log(
			`(${missing.length} spec-only types hidden — pass --show-missing to list)`,
		);
	}

	if (drift.length > 0) {
		console.log("\n=== DRIFT ===");
		for (const c of drift) {
			console.log(
				`  ${c.name}  (${relative(root, c.specFile)}:${c.line} <-> ${relative(root, c.srcFile)})`,
			);
			if (c.detail) {
				const lines = c.detail.split("\n").slice(0, 8);
				for (const l of lines) console.log(`    ${l.trim()}`);
			}
		}
	}

	if (showMissing && missing.length > 0) {
		console.log("\n=== MISSING IN CODE (informational) ===");
		for (const m of missing) {
			console.log(`  ${m.name}  (${relative(root, m.specFile)}:${m.line})`);
		}
	}

	return drift.length > 0 ? 1 : 0;
}

export interface DriftCheckOptions {
	specsDir: string;
	srcDir: string;
	tmpFile?: string;
}

export interface DriftCheckResult {
	checked: CheckedDecl[];
	missing: MissingDecl[];
}

export function runDriftCheck(opts: DriftCheckOptions): DriftCheckResult {
	const tmpFile =
		opts.tmpFile ?? join(tmpdir(), `spec-drift-check-${process.pid}.ts`);
	const srcMap = indexSrcExports(opts.srcDir);
	const blocks: SpecBlock[] = [];
	const counter = { n: 0 };
	for (const f of readdirSync(opts.specsDir)) {
		if (!f.endsWith(".md")) continue;
		blocks.push(...extractBlocks(join(opts.specsDir, f), counter));
	}
	const { checked, missing } = buildAssertionFile(blocks, srcMap, tmpFile);
	const diags = runTsc(tmpFile);
	classify(checked, diags);
	try {
		unlinkSync(tmpFile);
	} catch {
		// best effort
	}
	return { checked, missing };
}

interface CliArgs {
	specsDir: string;
	srcDir: string;
	showMissing: boolean;
	jsonPath: string | null;
}

function parseArgs(argv: string[], cwd: string): CliArgs {
	const resolveArg = (value: string): string =>
		isAbsolute(value) ? value : resolve(cwd, value);
	let specsDir = join(cwd, "specs");
	let srcDir = join(cwd, "src");
	let showMissing = false;
	let jsonPath: string | null = null;
	for (let i = 0; i < argv.length; i += 1) {
		const a = argv[i];
		if (a === "--specs-dir") {
			const next = argv[i + 1];
			if (!next) throw new Error("--specs-dir requires a path");
			specsDir = resolveArg(next);
			i += 1;
		} else if (a === "--src-dir") {
			const next = argv[i + 1];
			if (!next) throw new Error("--src-dir requires a path");
			srcDir = resolveArg(next);
			i += 1;
		} else if (a === "--show-missing") {
			showMissing = true;
		} else if (a === "--json") {
			const next = argv[i + 1];
			if (!next) throw new Error("--json requires a path");
			jsonPath = resolveArg(next);
			i += 1;
		} else if (a === "--help" || a === "-h") {
			console.log(
				"Usage: spec-drift [--specs-dir <path>] [--src-dir <path>] [--show-missing] [--json <path>]",
			);
			process.exit(0);
		} else {
			throw new Error(`Unknown argument: ${a}`);
		}
	}
	return { specsDir, srcDir, showMissing, jsonPath };
}

// Synthetic id for drift entries, used by loop-clean.sh for oscillation hashing.
// Stable across invocations as long as (name, spec_file, src_file) are unchanged.
function driftId(name: string, specFile: string, srcFile: string): string {
	const input = `spec-drift|${name}|${specFile}|${srcFile}`;
	return createHash("sha256").update(input).digest("hex").slice(0, 16);
}

function writeJsonReport(
	checked: CheckedDecl[],
	missing: MissingDecl[],
	exitCode: number,
	jsonPath: string,
	root: string,
): void {
	const drift = checked
		.filter((c) => c.status === "DRIFT")
		.map((c) => {
			const specFileRel = relative(root, c.specFile);
			const srcFileRel = relative(root, c.srcFile);
			return {
				id: driftId(c.name, specFileRel, srcFileRel),
				name: c.name,
				spec_file: specFileRel,
				spec_line: c.line,
				src_file: srcFileRel,
				detail: c.detail ?? "",
			};
		});
	const report = {
		skill: "spec-drift",
		exit_code: exitCode,
		checked_count: checked.length,
		drift,
		missing_count: missing.length,
	};
	writeFileSync(jsonPath, JSON.stringify(report, null, 2));
}

function main(): void {
	const cwd = process.cwd();
	const args = parseArgs(process.argv.slice(2), cwd);

	if (!existsSync(args.specsDir) || !existsSync(args.srcDir)) {
		const missing: string[] = [];
		if (!existsSync(args.specsDir))
			missing.push(relative(cwd, args.specsDir) || args.specsDir);
		if (!existsSync(args.srcDir))
			missing.push(relative(cwd, args.srcDir) || args.srcDir);
		console.log(
			`spec-drift: not a spec-driven project (missing ${missing.join(", ")}), skipping.`,
		);
		if (args.jsonPath) {
			writeJsonReport([], [], 0, args.jsonPath, cwd);
		}
		process.exit(0);
	}

	const { checked, missing } = runDriftCheck({
		specsDir: args.specsDir,
		srcDir: args.srcDir,
	});
	const exitCode = printReport(checked, missing, args.showMissing, cwd);
	if (args.jsonPath) {
		writeJsonReport(checked, missing, exitCode, args.jsonPath, cwd);
	}
	process.exit(exitCode);
}

// Only run main when invoked as a script, not when imported by tests.
// Use realpathSync + fileURLToPath to handle symlinks, macOS /private/var
// aliases, and non-POSIX path formats — a raw string equality on argv[1]
// fails silently in any of those cases and the script would exit 0 without
// running, masking drift in CI.
if (
	process.argv[1] &&
	fileURLToPath(import.meta.url) === realpathSync(process.argv[1])
) {
	main();
}
