#!/usr/bin/env python3
"""
Skill validation — structural checks + content quality + cross-references
"""

import sys
import re
import yaml
from pathlib import Path


# Template markers left behind by init_skill.py
TEMPLATE_MARKERS = [
    "[TODO: Complete and informative explanation",
    "[TODO: Choose the structure",
    "[TODO: 1-2 sentences explaining",
    "[TODO: Replace with the first main section",
    "[TODO: Add content here",
    'Delete this entire "Structuring This Skill" section',
]

# Example files generated by init_skill.py with their fingerprint strings
EXAMPLE_FILE_MARKERS = {
    "scripts/example.py": "This is a placeholder script",
    "references/api_reference.md": "This is a placeholder for detailed reference",
    "assets/example_asset.txt": "This placeholder represents where asset files",
}


def _strip_code_blocks(text):
    """Remove fenced code blocks to avoid false positives in cross-ref scanning."""
    return re.sub(r'```.*?```', '', text, flags=re.DOTALL)


def _find_file_references(body):
    """Extract resource paths referenced in SKILL.md body (outside code blocks)."""
    clean = _strip_code_blocks(body)
    pattern = r'(?:scripts|references|assets)/[\w._/-]+'
    return set(re.findall(pattern, clean))


def validate_skill_full(skill_path):
    """
    Full validation returning all issues.

    Returns:
        (errors: list[str], warnings: list[str])
    """
    skill_path = Path(skill_path)
    errors = []
    warnings = []

    # ── Structural checks ──

    skill_md = skill_path / 'SKILL.md'
    if not skill_md.exists():
        return ["SKILL.md not found"], []

    content = skill_md.read_text()
    if not content.startswith('---'):
        return ["No YAML frontmatter found"], []

    match = re.match(r'^---\n(.*?)\n---', content, re.DOTALL)
    if not match:
        return ["Invalid frontmatter format"], []

    frontmatter_text = match.group(1)
    body = content[match.end():].strip()

    try:
        frontmatter = yaml.safe_load(frontmatter_text)
        if not isinstance(frontmatter, dict):
            return ["Frontmatter must be a YAML dictionary"], []
    except yaml.YAMLError as e:
        return [f"Invalid YAML in frontmatter: {e}"], []

    ALLOWED_PROPERTIES = {'name', 'description', 'license', 'allowed-tools', 'metadata', 'compatibility'}
    unexpected_keys = set(frontmatter.keys()) - ALLOWED_PROPERTIES
    if unexpected_keys:
        errors.append(
            f"Unexpected key(s) in frontmatter: {', '.join(sorted(unexpected_keys))}. "
            f"Allowed: {', '.join(sorted(ALLOWED_PROPERTIES))}"
        )

    # Name validation
    name = frontmatter.get('name', '')
    if not name:
        errors.append("Missing 'name' in frontmatter")
    elif not isinstance(name, str):
        errors.append(f"Name must be a string, got {type(name).__name__}")
    else:
        name = name.strip()
        if not re.match(r'^[a-z0-9-]+$', name):
            errors.append(f"Name '{name}' should be kebab-case (lowercase letters, digits, hyphens only)")
        if name.startswith('-') or name.endswith('-') or '--' in name:
            errors.append(f"Name '{name}' cannot start/end with hyphen or contain consecutive hyphens")
        if len(name) > 64:
            errors.append(f"Name too long ({len(name)} chars, max 64)")

    # Description validation
    description = frontmatter.get('description', '')
    if not description:
        errors.append("Missing 'description' in frontmatter")
    elif not isinstance(description, str):
        errors.append(f"Description must be a string, got {type(description).__name__}")
    else:
        description = description.strip()
        if '<' in description or '>' in description:
            errors.append("Description cannot contain angle brackets (< or >)")
        if len(description) > 1024:
            errors.append(f"Description too long ({len(description)} chars, max 1024)")

    # Compatibility validation (optional)
    compatibility = frontmatter.get('compatibility', '')
    if compatibility:
        if not isinstance(compatibility, str):
            errors.append(f"Compatibility must be a string, got {type(compatibility).__name__}")
        elif len(compatibility) > 500:
            errors.append(f"Compatibility too long ({len(compatibility)} chars, max 500)")

    # ── Content quality checks ──

    # TODO in description
    if isinstance(description, str) and 'TODO' in description:
        errors.append("Description contains TODO marker — must be completed")

    # TODO markers in body
    todo_matches = re.findall(r'\[TODO:.*?\]', body)
    if todo_matches:
        errors.append(
            f"Body contains {len(todo_matches)} TODO marker(s) — "
            f"first: \"{todo_matches[0]}\""
        )

    # Template body not customized
    template_hits = [m for m in TEMPLATE_MARKERS if m in content]
    if template_hits:
        errors.append(
            f"Uncustomized template content ({len(template_hits)} marker(s)). "
            f"First: \"{template_hits[0][:60]}\""
        )

    # Body too short to be useful
    if len(body) < 50:
        errors.append(f"Body too short ({len(body)} chars) — add real content")

    # ── Cross-reference checks ──

    # Files referenced in SKILL.md that don't exist on disk
    # Warning (not error): prose examples may mention hypothetical paths
    referenced_files = _find_file_references(body)
    for ref in sorted(referenced_files):
        if not (skill_path / ref).exists():
            warnings.append(f"Referenced file not found: {ref}")

    # Files in resource dirs not referenced in SKILL.md (orphans)
    for resource_dir in ['scripts', 'references', 'assets']:
        dir_path = skill_path / resource_dir
        if dir_path.exists():
            for file_path in sorted(dir_path.rglob('*')):
                if file_path.is_file():
                    rel = str(file_path.relative_to(skill_path))
                    if rel not in referenced_files:
                        warnings.append(f"Unreferenced file: {rel}")

    # Uncustomized example files from init template
    for example_file, marker in EXAMPLE_FILE_MARKERS.items():
        file_path = skill_path / example_file
        if file_path.exists() and marker in file_path.read_text():
            warnings.append(f"Uncustomized template file: {example_file}")

    return errors, warnings


def validate_skill(skill_path):
    """Backward-compatible interface — returns (bool, str)."""
    errors, _ = validate_skill_full(skill_path)
    if errors:
        return False, errors[0]
    return True, "Skill is valid!"


if __name__ == "__main__":
    if len(sys.argv) != 2:
        print("Usage: python quick_validate.py <skill_directory>")
        sys.exit(1)

    errors, warnings = validate_skill_full(sys.argv[1])

    for e in errors:
        print(f"  ✗ {e}")
    for w in warnings:
        print(f"  ⚠ {w}")

    if errors:
        print(f"\nFAIL — {len(errors)} error(s), {len(warnings)} warning(s)")
        sys.exit(1)
    elif warnings:
        print(f"\nPASS — 0 errors, {len(warnings)} warning(s)")
    else:
        print("\nPASS — all checks OK")
    sys.exit(0)
